# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pylint-dev/pylint
    rev: v3.3.2  # Use the latest stable version
    hooks:
      - id: pylint
        additional_dependencies: [ pylint ]  # Ensure pylint is installed in the environment
        args: [--rcfile=.pylintrc]